apiVersion: k8s.natun.ai/v1alpha1
kind: DataConnector
metadata:
  name: clicks
spec:
  kind: streaming
  config:
    - name: kind
      value: kafka
    - name: brokers
      value: :9093
    - name: topics
      value: clickstream
    - name: consumer_group
      value: clicks-consumer-group
    - name: tls_disable
      value: "true"
