resources:
- core.yaml
- service.yaml
- webhook-server-cert.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: controller
  newName: ghcr.io/natun-ai/natun-core
  newTag: latest

replicas:
- count: 3
  name: controller-core

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
