---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: features.k8s.natun.ai
spec:
  group: k8s.natun.ai
  names:
    categories:
    - datascience
    kind: Feature
    listKind: FeatureList
    plural: features
    shortNames:
    - ft
    singular: feature
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Feature is the Schema for the features API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FeatureSpec defines the desired state of Feature
            properties:
              aggr:
                description: 'Aggr defines an aggregation on top of the underlying
                  feature-value. Aggregations will be calculated on time-of-request.
                  Users can specify here multiple functions to calculate the aggregation.
                  Valid values: - `count` - `min` - `mix` - `sum`` - `mean` (alias
                  for `avg`) - `avg`'
                items:
                  description: AggrType defines the type of aggregation
                  enum:
                  - count
                  - min
                  - max
                  - sum
                  - avg
                  - mean
                  type: string
                nullable: true
                type: array
              builder:
                description: Builder defines a building-block to use to build the
                  feature-value
                properties:
                  kind:
                    description: Kind defines the type of Builder to use to build
                      the feature-value.
                    type: string
                required:
                - kind
                type: object
                x-kubernetes-preserve-unknown-fields: true
              freshness:
                description: Freshness defines the age of a feature-value(time since
                  the value has set) to consider as *fresh*. Fresh values doesn't
                  require re-ingestion
                type: string
              primitive:
                description: 'Primitive defines the type of the underlying feature-value
                  that a Feature should respond with Valid values are: - `int` - `float`
                  - `string` - `timestamp - `[]int` - `[]float` - `[]string` - `[]timestamp`
                  - `headless`'
                enum:
                - int
                - float
                - string
                - timestamp
                - '[]int'
                - '[]float'
                - '[]string'
                - '[]timestamp'
                - headless
                type: string
              staleness:
                description: Staleness defines the age of a feature-value(time since
                  the value has set) to consider as *stale*. Stale values are not
                  fit for usage, therefore will not be returned and will REQUIRE re-ingestion.
                type: string
              timeout:
                description: Timeout defines the maximum ingestion time allowed to
                  calculate the feature value.
                nullable: true
                type: string
            required:
            - builder
            - freshness
            - primitive
            - staleness
            type: object
          status:
            description: FeatureStatus defines the observed state of Feature
            properties:
              connector:
                description: Connector is a reference for the DataConnector that this
                  Feature is associated with
                properties:
                  name:
                    description: Name is unique within a namespace to reference a
                      resource.
                    type: string
                  namespace:
                    description: Namespace defines the space within which the resource
                      name must be unique.
                    type: string
                type: object
              fqn:
                description: FQN is the Fully Qualified Name for the feature
                type: string
            required:
            - connector
            - fqn
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
