### Rename this file to `providers-creds.yaml` and change the following values
apiVersion: v1
kind: Secret
metadata:
  name: providers-creds
  namespace: raptor-system
data:
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  SNOWFLAKE_URI: <user>:<pass>@<account-id>/<db>/<schema>?warehouse=<warehouse-name>