---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: redis-standalone
  namespace: default
spec:
  # redisConfig:
  #   additionalRedisConfig: redis-external-config
  kubernetesConfig:
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    # redisSecret:
    #   name: redis-secret
    #   key: password
    # imagePullSecrets:
    #   - name: regcred
#  redisExporter:
#    enabled: false
#    image: quay.io/opstree/redis-exporter:1.0
#    imagePullPolicy: Always
#    resources:
#      requests:
#        cpu: 100m
#        memory: 128Mi
#      limits:
#        cpu: 100m
#        memory: 128Mi
    # Environment Variables for Redis Exporter
    # env:
    # - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    #   value: "true"
    # - name: UI_PROPERTIES_FILE_NAME
    #   valueFrom:
    #     configMapKeyRef:
    #       name: game-demo
    #       key: ui_properties_file_name
    # - name: SECRET_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: mysecret
    #       key: username
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  # nodeSelector:
  #   kubernetes.io/hostname: minikube
  # securityContext: {}
  # priorityClassName:
  # affinity:
  # Tolerations: []

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-standalone
    redis_setup_type: standalone
    role: standalone
  name: redis-standalone-external
  namespace: default
spec:
  ports:
    - name: redis-client
      port: 6379
      protocol: TCP
      targetPort: 6379
      nodePort: 32094
  selector:
    app: redis-standalone
    redis_setup_type: standalone
    role: standalone
  type: NodePort